Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.): 
1. What does Pandas stand for? *Either 'Panel Data' or 'Python Data Analysis'*
2. What are the 2 collections used in Pandas? *Series and Dataframes*
3. Name 4 things Pandas can do for us. *Load, model, prepare, manipulate, and model data*
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method? *inplace = true*
5. What is a CSV? *Comma Separated Value (CSV) files store data in an extremely minimalistic way using only commas and values to store data in columns and rows.*
6. When cleaning data what values do we not like in our data? *NULLs*

In [3]:
# 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np
array1 = np.arange(12).reshape(((2,3,2)))
print("The array1 array ...\n", array1)

The array1 array ...
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
# 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
array2 = np.linspace(0, 20, num=6)
print("Array2 ...", array2)

Array2 ... [ 0.  4.  8. 12. 16. 20.]


In [7]:
# 9. Make a Deep Copy of the above array
import copy
array2 = np.linspace(0, 20, num=6)
array3= copy.deepcopy(array2)

print("Array2 ...\n", array2)
print("\nArray3, a deepcopy ...\n", array3)

Array2 ...
 [ 0.  4.  8. 12. 16. 20.]

Array3, a deepcopy ...
 [ 0.  4.  8. 12. 16. 20.]


In [15]:
# 10. Concatenate these 3 arrays into a new array named 'newArray'...
array4 = ([[25, 16]])
array5 = ([[11, 2], [13, 4]])
array6 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array4, array5, array6), axis=0)
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [20]:
# 11. Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [27]:
# 12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
print("I'm not seeing an array called 'reshapedArray' anywhere.")

I'm not seeing an array called 'reshapedArray' anywhere.


In [29]:
# 13. Combine and sort the following arrays into one called 'comboArray'
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three), axis=0))
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [80]:
# 14. Take 'comboArray' and perform the following slicing activities:
# print sec1 - the 2nd element
print(comboArray[1])
# print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])
# print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:14])
# print sec4 - the last 6 elements
print(comboArray[-6:])
# print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[-28:-10])
# print sec6 - from #20 every even element to the end
print(comboArray[16::2])
# print sec7 - from the last element moving forward, every 5th element.
print("I'm not totally sure what this is asking, but here is my best guess: ", comboArray[3::5])

1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
I'm not totally sure what this is asking, but here is my best guess:  [ 3 10 15 22 27]


In [86]:
# 15. Using `Series`, create a `DataFrame` that looks like this:

#    | Ingredients | Quantity | Unit |
#    |----|----|----|
#    | Flour | 4 | cups |
#    | Milk | 1 | cup |
#    | Eggs | 2 | large |
#    | Spam | 1 | can |

#    Name: Dinner, dtype: object

import pandas as pd

Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"], name='Ingredients')
Quantity = pd.Series([4,1,2,1],name='Quantity')
Unit = pd.Series(["cups","cup","large","can"],name='Unit')

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)
print(Dinner)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [ ]:
# 16. Take this data and create a DataFrame named studentData
# {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
# 'Height': [5.1, 6.2, 5.1, 5.2],
# 'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
# 'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
# 'Age': [21, 23, 24, 21],
# 'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
# 'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']

Ingredients = pd.Series(["Flour","Milk","Eggs","Spam"], name='Ingredients')
Quantity = pd.Series([4,1,2,1],name='Quantity')
Unit = pd.Series(["cups","cup","large","can"],name='Unit')